# 本地开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/smartrecord?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
  data:
    redis:
      host: localhost
      port: 16379

app:
  jwt:
    secret: your-256-bit-secret-key-here-change-in-production
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t8gKSckJYZjUqivuhPi
    access-key-secret: GfCTwLAUSFerci7Ov5NKGGYS5w8YoE
    bucket-name: smartrecord
  llm:
    api-url: https://token-plan-cn.xiaomimimo.com/v1/chat/completions
    api-key: tp-cl8s6teu6pdyb2iquraslrka4zfpoc5an6e87isdffejcmnp
    model: mimo-v2.5
  tts:
    mimo-voice: 冰糖

wechat:
  appid: wx9d93ece2b67f812b
  secret: 5bcbb76c58c59b466acc90a86e4864c6

tts:
  edge-tts-cmd: /Users/happy/.local/bin/edge-tts
